hash-format = "sha256"

[[files]]
file = ".envrc"
hash = "1d26c74fd25a4c3dbb09e029fc609588da499fd4af2a41c88f6316c7f8c54cf1"

[[files]]
file = "config/iris.properties"
hash = "396c4896484b87c8628f07a8083af78855fa441835449d4a94d8ea86b84a40ba"

[[files]]
file = "config/itemscroller.json"
hash = "b9a1997727d4a3001cf589901099f409a54def6e76b23bb81904ee15f4b7c2d3"

[[files]]
file = "config/litematica.json"
hash = "2ce533c7d3b123ffbd5df1b16c630a3dadc23c0bd11d8c739f58f0f45bb60634"

[[files]]
file = "config/litematica/litematica_localhost.json"
hash = "c5084e511824ed9f2f38764243b970bd4c7d1047c5fa450b4f4e1c6a2cf9622e"

[[files]]
file = "config/litematica/litematica_localhost_dim_minecraft_overworld.json"
hash = "4a6809e2e3fd89774626b695a48533eaeee73131af4f27333f09af1807eae2bf"

[[files]]
file = "config/litematica/litematica_localhost_dim_minecraft_the_end.json"
hash = "4a6809e2e3fd89774626b695a48533eaeee73131af4f27333f09af1807eae2bf"

[[files]]
file = "config/litematica/litematica_localhost_dim_minecraft_the_nether.json"
hash = "4a6809e2e3fd89774626b695a48533eaeee73131af4f27333f09af1807eae2bf"

[[files]]
file = "config/litematica/litematica_nerduniverse.duckdns.org.json"
hash = "c5084e511824ed9f2f38764243b970bd4c7d1047c5fa450b4f4e1c6a2cf9622e"

[[files]]
file = "config/litematica/litematica_nerduniverse.duckdns.org_dim_minecraft_overworld.json"
hash = "c6e3dcc4f1f37009b5d9bafd8fe6721bfc62cb5948f0ab0d64175ade83a9e5d6"

[[files]]
file = "config/litematica/litematica_nerduniverse.duckdns.org_dim_minecraft_the_end.json"
hash = "4a6809e2e3fd89774626b695a48533eaeee73131af4f27333f09af1807eae2bf"

[[files]]
file = "config/litematica/litematica_nerduniverse.duckdns.org_dim_minecraft_the_nether.json"
hash = "c6e3dcc4f1f37009b5d9bafd8fe6721bfc62cb5948f0ab0d64175ade83a9e5d6"

[[files]]
file = "config/litematica/litematica_new_world.json"
hash = "12174fd2e7b7105aa4aa98a486df7baa470fd770ff30a731cf314c4fd571701a"

[[files]]
file = "config/litematica/litematica_new_world_dim_minecraft_overworld.json"
hash = "4a6809e2e3fd89774626b695a48533eaeee73131af4f27333f09af1807eae2bf"

[[files]]
file = "config/malilib.json"
hash = "13b137a7e5d3194ccd24f617731ba4aac32237d69067f1f5b8bbb1160e6efe76"

[[files]]
file = "config/minihud.json"
hash = "7e069df522fd7edb611b9b917b1fbccb7b26d9429ff2ec4190513c2e288b8ca1"

[[files]]
file = "config/minihud/localhost.json"
hash = "7d379de5ad06b4471e4b7e62970340437662e77453dd1bacb3bc90f975403464"

[[files]]
file = "config/minihud/localhost_dim_minecraft_overworld.json"
hash = "d52eed27fd155e3c847593668511315c745ad9113ebac783b827f8411c36715c"

[[files]]
file = "config/minihud/localhost_dim_minecraft_the_end.json"
hash = "dd81d0abfde5de7a306ad024b0e6dc984435eb7f14502199cff365a767dbfb2c"

[[files]]
file = "config/minihud/localhost_dim_minecraft_the_nether.json"
hash = "dd81d0abfde5de7a306ad024b0e6dc984435eb7f14502199cff365a767dbfb2c"

[[files]]
file = "config/minihud/nerduniverse.duckdns.org.json"
hash = "7d379de5ad06b4471e4b7e62970340437662e77453dd1bacb3bc90f975403464"

[[files]]
file = "config/minihud/nerduniverse.duckdns.org_dim_minecraft_overworld.json"
hash = "dd81d0abfde5de7a306ad024b0e6dc984435eb7f14502199cff365a767dbfb2c"

[[files]]
file = "config/minihud/nerduniverse.duckdns.org_dim_minecraft_the_end.json"
hash = "dd81d0abfde5de7a306ad024b0e6dc984435eb7f14502199cff365a767dbfb2c"

[[files]]
file = "config/minihud/nerduniverse.duckdns.org_dim_minecraft_the_nether.json"
hash = "dd81d0abfde5de7a306ad024b0e6dc984435eb7f14502199cff365a767dbfb2c"

[[files]]
file = "config/minihud/new_world.json"
hash = "7d379de5ad06b4471e4b7e62970340437662e77453dd1bacb3bc90f975403464"

[[files]]
file = "config/minihud/new_world_dim_minecraft_overworld.json"
hash = "dd81d0abfde5de7a306ad024b0e6dc984435eb7f14502199cff365a767dbfb2c"

[[files]]
file = "config/peek/peek.properties"
hash = "bfa5754e7f8f53ecc85feb1f0eeafde3430d2ea47bc64701d662500c7140bbbd"

[[files]]
file = "config/sdrp-common.json"
hash = "fc5ca865f4f027189b5894c421fd99588e0916f27915d29bb1dcf068a510a28f"

[[files]]
file = "config/tweakeroo.json"
hash = "a53c34fb39f3384eb15b3c799ed0656e620e0525cf336b2ad615eb24cbcb949b"

[[files]]
file = "config/xaerominimap-common.txt"
hash = "1dcee38470c2939f7265891203775b7631c81822bf2506a451727fcaaf2cc4a2"

[[files]]
file = "config/xaerominimap.txt"
hash = "54774cf954b6dc94b2ea96101cc1773a269e51f0c381607ad6c301375acab9a3"

[[files]]
file = "config/xaerominimap_entities.json"
hash = "c63fa9862b71e4d7d39f0ba3c214ec8482c622d960574003eabe56dd021cbead"

[[files]]
file = "config/xaeropatreon.txt"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "config/xaeroworldmap-common.txt"
hash = "103979a8e59e396f99fb8646c4f8a690c2d743ca3744a2eb8f663b3102b7498c"

[[files]]
file = "config/xaeroworldmap.txt"
hash = "6028733f967d0d0f6a80dd236d3dcc7d2446912c719ab9a7d3f83d8624d9b92d"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "904365e7891802e522e5a35189b7039e18f56a22ab30bd99af59b97ec4b7468e"
metafile = true

[[files]]
file = "mods/anti-xray.pw.toml"
hash = "7ffd2cbb973d987d543b36f12cc9362baae07b0983b83a8292f063ed4287f9a9"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "ed50f3b3feba91fa31915aefb40690bc322f37be83490e6b59a443e83a46a542"
metafile = true

[[files]]
file = "mods/axiom.pw.toml"
hash = "b1e08d3a6db8777433227b2b300c89795d7baced15a012fe256aaddef74e91b6"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "5ab81359d4654812c2f4dd40f6db5bb51e217a228827d5cc351a40611f05d7de"
metafile = true

[[files]]
file = "mods/bundles-beyond.pw.toml"
hash = "7908a5bd9db4ffcf529f5df1e588982441996082ebe3b8536ba831513dcc5865"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "bf1cd023d328ab35eb85ffeffc55d2177dc603b28f5e168f87dd15d169d09a3f"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "092508af534efeb380b9551663980ab1f701d88583a63227d02cb02843335f7a"
metafile = true

[[files]]
file = "mods/clientsort.pw.toml"
hash = "f08478092de1b182154cccb4208a397b6ce0ec6027f563a2adce4203d9b51884"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "72f3dbfcfbf16d8437d865b090c4338cf32de86f290e8e8dde5626cb301bb4c7"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "8395078cc9b359cf76e0bf950c57b886101446d1c7893a733c9cc16fd6c7d2f8"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "3a96a1e5bef30c16a8738c2a8acf54693225122424c39fa06f589a11ccc83b90"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "6adf5f512651c200a320219c32a3a51c8b95e219206f64b99cb93940d51b2cfa"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "cf6edd71a012b437bca4bcac93c44d1109632db31b5f638d28b58fa77cf771b5"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "76a12a836d4c7f0f943a1e391dd2d7b5c4673caa497fff16593d49449376b117"
metafile = true

[[files]]
file = "mods/herenthere.pw.toml"
hash = "0d5730b227ad429165ef6b2bbe269e5123b71221bc6b8b0efac56232ace2b0c6"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "dc930299b4c11cbd31712a3b91231bac4be1f34d00a464bfbe1a0674f5187d11"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "442468b81b595bb843af8ca225b51dbf5389f3ddaf07c009d1d2e6bc9f8d7610"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "256153cf388712677ab3812461006be256f0d4dbe3ad3505457722a85b4f2312"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "88a36b21d538d44aca7dd0a7e5ad8c09b1b263be3f4381e3bb22bc9f94ee7290"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "ebde302faa068ace4a27bb1228fabdbec05651a418c5109845a0e84141fb018f"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "6bb2e02cb1d2feb46ea384229d7f8795125e8afcf8adafe44efaa777506e6175"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "6dbca2c20d66b076bb4e8959ea0e26887991acf48f785aae402e066d5e3eb6ea"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "4626f4c13b47099ed0466cc50e1fb526e9b00de88a39e5e11e66be142ff38013"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "4d801184db14d95a0084083f61c6331e2c1090203b5639809ea1471effc9417d"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "f61bd9fbfa3fcc5d8267b5cbe6af08c93385752ddc6e6b74df0fbcfd5747e413"
metafile = true

[[files]]
file = "mods/tweakermore.pw.toml"
hash = "060b425b0055d87f793f7f8325aa8ad637cb84dd4b33a2908646372e201d5f9b"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "f7148ee0560f056fe5d60984527b370b0fec15d6bc427778021e68b89220b07c"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "34fea802d614ca9d67ee54693a23ba5d91a3728510db404c88140098eb38860f"
metafile = true

[[files]]
file = "options.txt"
hash = "40efb3f53dabcc091e4fa10b9c35d24771e58373979765af623e42467a12ea79"

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "134b3cee2ac2b5c5b9d02d8d70e8e4ba32c7c241f5bc51209521831a7c254e22"
metafile = true
