hash-format = "sha256"

[[files]]
file = "config/iris.properties"
hash = "396c4896484b87c8628f07a8083af78855fa441835449d4a94d8ea86b84a40ba"

[[files]]
file = "config/itemscroller.json"
hash = "b9a1997727d4a3001cf589901099f409a54def6e76b23bb81904ee15f4b7c2d3"

[[files]]
file = "config/litematica.json"
hash = "2ce533c7d3b123ffbd5df1b16c630a3dadc23c0bd11d8c739f58f0f45bb60634"

[[files]]
file = "config/litematica/litematica_localhost.json"
hash = "c5084e511824ed9f2f38764243b970bd4c7d1047c5fa450b4f4e1c6a2cf9622e"

[[files]]
file = "config/litematica/litematica_localhost_dim_minecraft_overworld.json"
hash = "4a6809e2e3fd89774626b695a48533eaeee73131af4f27333f09af1807eae2bf"

[[files]]
file = "config/litematica/litematica_localhost_dim_minecraft_the_end.json"
hash = "4a6809e2e3fd89774626b695a48533eaeee73131af4f27333f09af1807eae2bf"

[[files]]
file = "config/litematica/litematica_localhost_dim_minecraft_the_nether.json"
hash = "4a6809e2e3fd89774626b695a48533eaeee73131af4f27333f09af1807eae2bf"

[[files]]
file = "config/litematica/litematica_nerduniverse.duckdns.org.json"
hash = "c5084e511824ed9f2f38764243b970bd4c7d1047c5fa450b4f4e1c6a2cf9622e"

[[files]]
file = "config/litematica/litematica_nerduniverse.duckdns.org_dim_minecraft_overworld.json"
hash = "c6e3dcc4f1f37009b5d9bafd8fe6721bfc62cb5948f0ab0d64175ade83a9e5d6"

[[files]]
file = "config/litematica/litematica_nerduniverse.duckdns.org_dim_minecraft_the_end.json"
hash = "4a6809e2e3fd89774626b695a48533eaeee73131af4f27333f09af1807eae2bf"

[[files]]
file = "config/litematica/litematica_nerduniverse.duckdns.org_dim_minecraft_the_nether.json"
hash = "c6e3dcc4f1f37009b5d9bafd8fe6721bfc62cb5948f0ab0d64175ade83a9e5d6"

[[files]]
file = "config/litematica/litematica_new_world.json"
hash = "12174fd2e7b7105aa4aa98a486df7baa470fd770ff30a731cf314c4fd571701a"

[[files]]
file = "config/litematica/litematica_new_world_dim_minecraft_overworld.json"
hash = "4a6809e2e3fd89774626b695a48533eaeee73131af4f27333f09af1807eae2bf"

[[files]]
file = "config/malilib.json"
hash = "13b137a7e5d3194ccd24f617731ba4aac32237d69067f1f5b8bbb1160e6efe76"

[[files]]
file = "config/minihud.json"
hash = "7e069df522fd7edb611b9b917b1fbccb7b26d9429ff2ec4190513c2e288b8ca1"

[[files]]
file = "config/minihud/localhost.json"
hash = "7d379de5ad06b4471e4b7e62970340437662e77453dd1bacb3bc90f975403464"

[[files]]
file = "config/minihud/localhost_dim_minecraft_overworld.json"
hash = "d52eed27fd155e3c847593668511315c745ad9113ebac783b827f8411c36715c"

[[files]]
file = "config/minihud/localhost_dim_minecraft_the_end.json"
hash = "dd81d0abfde5de7a306ad024b0e6dc984435eb7f14502199cff365a767dbfb2c"

[[files]]
file = "config/minihud/localhost_dim_minecraft_the_nether.json"
hash = "dd81d0abfde5de7a306ad024b0e6dc984435eb7f14502199cff365a767dbfb2c"

[[files]]
file = "config/minihud/nerduniverse.duckdns.org.json"
hash = "7d379de5ad06b4471e4b7e62970340437662e77453dd1bacb3bc90f975403464"

[[files]]
file = "config/minihud/nerduniverse.duckdns.org_dim_minecraft_overworld.json"
hash = "dd81d0abfde5de7a306ad024b0e6dc984435eb7f14502199cff365a767dbfb2c"

[[files]]
file = "config/minihud/nerduniverse.duckdns.org_dim_minecraft_the_end.json"
hash = "dd81d0abfde5de7a306ad024b0e6dc984435eb7f14502199cff365a767dbfb2c"

[[files]]
file = "config/minihud/nerduniverse.duckdns.org_dim_minecraft_the_nether.json"
hash = "dd81d0abfde5de7a306ad024b0e6dc984435eb7f14502199cff365a767dbfb2c"

[[files]]
file = "config/minihud/new_world.json"
hash = "7d379de5ad06b4471e4b7e62970340437662e77453dd1bacb3bc90f975403464"

[[files]]
file = "config/minihud/new_world_dim_minecraft_overworld.json"
hash = "dd81d0abfde5de7a306ad024b0e6dc984435eb7f14502199cff365a767dbfb2c"

[[files]]
file = "config/peek/peek.properties"
hash = "bfa5754e7f8f53ecc85feb1f0eeafde3430d2ea47bc64701d662500c7140bbbd"

[[files]]
file = "config/sdrp-common.json"
hash = "fc5ca865f4f027189b5894c421fd99588e0916f27915d29bb1dcf068a510a28f"

[[files]]
file = "config/tweakeroo.json"
hash = "a53c34fb39f3384eb15b3c799ed0656e620e0525cf336b2ad615eb24cbcb949b"

[[files]]
file = "config/xaerominimap-common.txt"
hash = "1dcee38470c2939f7265891203775b7631c81822bf2506a451727fcaaf2cc4a2"

[[files]]
file = "config/xaerominimap.txt"
hash = "54774cf954b6dc94b2ea96101cc1773a269e51f0c381607ad6c301375acab9a3"

[[files]]
file = "config/xaerominimap_entities.json"
hash = "c63fa9862b71e4d7d39f0ba3c214ec8482c622d960574003eabe56dd021cbead"

[[files]]
file = "config/xaeropatreon.txt"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "config/xaeroworldmap-common.txt"
hash = "103979a8e59e396f99fb8646c4f8a690c2d743ca3744a2eb8f663b3102b7498c"

[[files]]
file = "config/xaeroworldmap.txt"
hash = "6028733f967d0d0f6a80dd236d3dcc7d2446912c719ab9a7d3f83d8624d9b92d"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "7467a101c890769c5d0796e1a4d646074ef8f96c9c1d2995dbb0f3972ea49916"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1fc1e482945dff68e6aab34b22d61d054a6177869408ed4af3fef6117a33faab"
metafile = true

[[files]]
file = "mods/axiom.pw.toml"
hash = "5d803700375154c02bfa9e7d3f64b634708568f4d22cd3671cddcd9b3c7d2ab5"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "6d717e11f5a11194004d8879b5c1e46448394855211ce8ac1937ae40895f2c27"
metafile = true

[[files]]
file = "mods/bundles-beyond.pw.toml"
hash = "0468ce45030e77dc9b3a848b01014e8bb7a3fb7f65bc8db3efde2d0b438498d3"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "4ee1808a7fb319d469dece5752cedb05dacb9afbe48021fa664f54b8c83fdc45"
metafile = true

[[files]]
file = "mods/chat-calc-kt.pw.toml"
hash = "0742eae510d3dc9249883092efee4defdd04d4689e3db294e0be18bb9df84f2f"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "0e073702f4562edac6258fd01f8b921628adf48fdd7e70209d93f4978753a0ce"
metafile = true

[[files]]
file = "mods/cherished-worlds.pw.toml"
hash = "9d07c9ba99c427bc750413e68552dcb497c6aec4f2483bf4a46bd93a19e886a3"
metafile = true

[[files]]
file = "mods/clientsort.pw.toml"
hash = "526b3ebca5d5c7320c6a919c5db42743e3ffd51d7e4df4218cba14fd470a59f9"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "717d8ac591dba59be4767a179e1359747561e54ccfcac42161fd6bf54339a78b"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
hash = "5ca99808c48e56205c8b02adfefa6489f9108eb25511f00721125cdc9fafe0e9"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "a43e3d76464a16015d62ba08d51da734f92377f0889c3984656d6d5739d284b2"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "63fe49aaee4880ff28e30aa558084f7322d5ec2bf110022bc5ae89a9be5cf2bf"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "5443c56a46d7fca84a1f96dc58315951a24cf8954f059aa35f213f28214d468d"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "cbda4f1881cfb9f054395a3db225df4202d1f2e7bd0ed27d803b837fcf728621"
metafile = true

[[files]]
file = "mods/fabric-carpet.pw.toml"
hash = "a2aac34aa73dee6f2c992f37758557ebd4289e8ace7029ca9ff65310b426d3e9"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "186a261ded1911abf559dce21b22eadc1e96de7767982e58f458b82a89a924ba"
metafile = true

[[files]]
file = "mods/herenthere.pw.toml"
hash = "bbf42135d2c585de8f7fcc04802de638631a43fe34d921a470e1f6351d7400e6"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "5a6ee9ae2de75743aa027eb753ac9c3cb92305df67bde8fe2cefdd2df0eb49d7"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "4ed061d122cb39f34ed730984c7bcf03437250f24a21975203bb4598d7d86a14"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "47e38eeda17a991d3201448e71f68081893c8e7aee15b44088dc86eacfc8ca43"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "84957275e9dc6f07f4244ce3303536e3d73b0e72eb1696ccd024168a52c29c98"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "df5ce30f6ac464f7b06400e03568d2b9087dd1849fd8c21a2381fe2f666338b6"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "2d373a1128cdb01a77053c64d5d6a64cf76c2d68da0529b2cc0f2dd6f8371767"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "b261880bd245c83c51b729199452da12b0766a4aa0210fc79d0c48161cbfcc49"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "5dd45d5fd5e1ae2bd521b93a70b83c69b57ada18f424c6562d8c6ea9980cfb3e"
metafile = true

[[files]]
file = "mods/nvidium-0.4.2-beta3-1.21.9-1.21.10.jar"
hash = "9195fd8c4f27a1d4dcb5fb79e7827ef377c28ad491e42655a5dde49e6d774ff7"

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "4626f4c13b47099ed0466cc50e1fb526e9b00de88a39e5e11e66be142ff38013"
metafile = true

[[files]]
file = "mods/simple-discord-rpc.pw.toml"
hash = "1682add4f33743fe9c60cbae1342e02303d475b652948eeee9071c2be7119f08"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "279ea1bb4b776be9176fe34416e2132e37abfce4483def54177091cc0f2faade"
metafile = true

[[files]]
file = "mods/tweakermore.pw.toml"
hash = "52db049cc81d85ae0fb99308e66e3f272c73bd05120e61e3f94ca23bddb8e490"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "c5092ec9a074c3afcc2312c985d0829e023dcfa3524597ec1c4902359d5c78dc"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "a7d0bbc50957cfb31069dc6ae4ede843f64fa40a34613986bc7adbb856ffb71d"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "121b4fa5f12aef9a36418922a8be02aa715ad40347165e31dcdf293f16019519"
metafile = true

[[files]]
file = "options.txt"
hash = "40efb3f53dabcc091e4fa10b9c35d24771e58373979765af623e42467a12ea79"

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "134b3cee2ac2b5c5b9d02d8d70e8e4ba32c7c241f5bc51209521831a7c254e22"
metafile = true
