hash-format = "sha256"

[[files]]
file = ".envrc"
hash = "1d26c74fd25a4c3dbb09e029fc609588da499fd4af2a41c88f6316c7f8c54cf1"

[[files]]
file = "config/clientsort.json"
hash = "215bfc07630f8ab3bcb9b679301e99af01b519887d474ae2dcfe78f7c56f017a"

[[files]]
file = "config/iris.properties"
hash = "396c4896484b87c8628f07a8083af78855fa441835449d4a94d8ea86b84a40ba"

[[files]]
file = "config/itemscroller.json"
hash = "b9a1997727d4a3001cf589901099f409a54def6e76b23bb81904ee15f4b7c2d3"

[[files]]
file = "config/litematica.json"
hash = "ad6f627f640b89869bdcd5078f5530eb21c48feb3044ccb0fee39f2303bf05a7"

[[files]]
file = "config/malilib.json"
hash = "13b137a7e5d3194ccd24f617731ba4aac32237d69067f1f5b8bbb1160e6efe76"

[[files]]
file = "config/minihud.json"
hash = "474f4c3794c28923f97152f5a2fa9465bc54239277381daf342e3efcfefb7e2c"

[[files]]
file = "config/peek/peek.properties"
hash = "bfa5754e7f8f53ecc85feb1f0eeafde3430d2ea47bc64701d662500c7140bbbd"

[[files]]
file = "config/sdrp-common.json"
hash = "fc5ca865f4f027189b5894c421fd99588e0916f27915d29bb1dcf068a510a28f"

[[files]]
file = "config/tweakeroo.json"
hash = "5a6a877c576995c17ee1e66778d36bfdcc0fde65c1bc71d943671837ba037a2b"

[[files]]
file = "config/xaerominimap.txt"
hash = "54774cf954b6dc94b2ea96101cc1773a269e51f0c381607ad6c301375acab9a3"

[[files]]
file = "config/xaeroworldmap.txt"
hash = "6028733f967d0d0f6a80dd236d3dcc7d2446912c719ab9a7d3f83d8624d9b92d"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "904365e7891802e522e5a35189b7039e18f56a22ab30bd99af59b97ec4b7468e"
metafile = true

[[files]]
file = "mods/accurate-block-placement-reborn.pw.toml"
hash = "a585ec0a1693b2554bd2f04c15bb9d08ffaa2a0c5a74c39bebc8e7e4defe5dc8"
metafile = true

[[files]]
file = "mods/anti-xray.pw.toml"
hash = "7ffd2cbb973d987d543b36f12cc9362baae07b0983b83a8292f063ed4287f9a9"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "ca3ae2608987185814c118388f28057f729d866ee1abbc97f3650141d213fa35"
metafile = true

[[files]]
file = "mods/autorun.pw.toml"
hash = "a6a3f8e8b127583f0dddf76c4a9aa5e946074c80e0aea94e3453e12e7952a542"
metafile = true

[[files]]
file = "mods/axiom.pw.toml"
hash = "b1e08d3a6db8777433227b2b300c89795d7baced15a012fe256aaddef74e91b6"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "b72d00d529ec694ae354b73f6b36d4ec2b830c60c05cc31f46d00ac7ddf8a26b"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "17e7de63579b066cea4b6db60318617956c1925891edc562085cd72544a763b9"
metafile = true

[[files]]
file = "mods/bigshot.pw.toml"
hash = "d664a21bceb31aae94ef5c73898b0bd5387fd8bef59d24e9ecd54ebe6d53d0c5"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "5ab81359d4654812c2f4dd40f6db5bb51e217a228827d5cc351a40611f05d7de"
metafile = true

[[files]]
file = "mods/bundles-beyond.pw.toml"
hash = "15405277b8318d28990a64d0a75fa0082597a313c9f9aa20f0f32b8285a85caf"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "a8f073ab0640d9e501fe3fc95d282306000fd6eab3186fd682269c0d0913b307"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "6ebb236b2a46dbf564aa2760a68027703e44105ab18e77ea76c0fe2323a9bafb"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "3574ca8f34cf9e005046179d449af1abd0c7475d3889d2cb2bc187ff28b360d1"
metafile = true

[[files]]
file = "mods/chatanimation.pw.toml"
hash = "9854603f767980c514aefe9c391a6d3fa89dc6be18d23ab462f2a3bbabe7652c"
metafile = true

[[files]]
file = "mods/clientsort.pw.toml"
hash = "45cce9573e88c0e64e9b5f3985ad379bf65de5843b5468d924888b10c3ee9875"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a06ef129798265e0d7249426fb0ed5c506725b0460dc3dfdb975b8978480895e"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "c2a61b492dd0d7a156e15b7572adb40552b94c09658cc3c6d7faf99288d094c7"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "d53b229a5588d33a8dac8682cba4371b22b2cbe2541c7129506cfbd44daaf6f8"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "716b671d0b15ea17c788c571620eac83207bb2b6e8dbe0d33319838478f21efc"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "479cc9008a66ce4dea0b0be0f749a986d73f5fe778516d6682a5202e19706179"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "7b83af5380faba6641a6fdf27e239eba79846f6b66a65da810860a8cb1e86ee4"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "c23a1be7641341478b09c5c4f835b5e024a246f9e8521e92905bcab0d0e8cce0"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "45abf05e1cc90006aeb65e4e1bbe97da5a1984f547ea8028a077dae68af0ac11"
metafile = true

[[files]]
file = "mods/fabric-carpet.pw.toml"
hash = "23e7bbed95cb3490dcf81a18212067e0150eeb6feb046871fdfee3467a9e56d7"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/fadeless.pw.toml"
hash = "33751edd5b63fdc4d8c51e19a74013efc600807ad8cf773d1512072b97c8ecd7"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "87dea750205910be6e5184ca4cdc3a3f2f439364435408b8e7a1036fdf3c28fc"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "816b735b2ad505476201800a99f527e61b392b712b9d20ca9edcce05f412fe87"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "b22f1d052eee2810fda73d850dd6f425a1214965e03a5a9dada421abfe74603b"
metafile = true

[[files]]
file = "mods/herenthere.pw.toml"
hash = "0d5730b227ad429165ef6b2bbe269e5123b71221bc6b8b0efac56232ace2b0c6"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "9e7bacd24307639764f3b74ae35a562b6becf2701637b816de0eaae15ab714c0"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "276947b1f9933ca2220a00736aba177e4034ca9a45cad9f258abf762fdb3bb0b"
metafile = true

[[files]]
file = "mods/item-scroller.pw.toml"
hash = "8643786cd883f7686a11f2bcc773acbe6559a7d3d13af3ed690e8d7fa58ef343"
metafile = true

[[files]]
file = "mods/ixeris.pw.toml"
hash = "c8bac36cc7a80745ef1e43b80b5051f6ef2596c06bdf025676fb03ad62759532"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "61e1149d5642bb6bd3d2c718054107fa7a6f1b1044f5573d5ecbab3b94f9e281"
metafile = true

[[files]]
file = "mods/litematicdownloader.pw.toml"
hash = "e1a2ce44038c3b964d1c1af4d98e5ece5dd254b1cac49bfe4d1a3becb2fa856b"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "0e87ab10adb3db84b1d6d2ce8bdd7158878b56c965055056b10ad6cde2634568"
metafile = true

[[files]]
file = "mods/llitematica-quick-share-addon.pw.toml"
hash = "5121d59e9f3fb2acec506149f942a0dd39354187df0ac744b3efc300f1ed89f0"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "6324b634d5e464cf2606cce4e1d9b923701cad31764858d982fe0738129e0e4e"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "6d26fbac2dca7845d5de9e5fbbe3dbcb7541ccb952e4f5f14a92e618d5448965"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "51ff93e279e03cb3cd77a5be0df777cdcd975d35b5149180d9dc724e47168c76"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "cd25851cbdaad2dd1957a8086ce54aa4bd3c45be75e1ba49168a54fafbd87898"
metafile = true

[[files]]
file = "mods/peek.pw.toml"
hash = "a7ed3b70eee552acb382d218b9ab840d6d8d81fac7491db9d146692c4d870389"
metafile = true

[[files]]
file = "mods/ping-view.pw.toml"
hash = "5feb5943b2d67736363b69cd5b14021573f835f7c9dd376f7597b03ba83030f7"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "de8ac33882f1c4c83051c096e7cf181061b8c2157b899ebf023e7ac449e09d6d"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "548a21f091f48b62c91d69a3857648abc6cc70ea18ebeb2d0b649a6576773a27"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "936e9028071f4e49ecd551aadab4c161f9a7143764b4cc89f8077296bd8645a6"
metafile = true

[[files]]
file = "mods/shuttfup.pw.toml"
hash = "d44432512af8fc6992c273a01e26b9067d26f52b02f4f252476832b69d25851c"
metafile = true

[[files]]
file = "mods/signalloss.pw.toml"
hash = "743040f377b4f1e5b8f59764eeca73a4c2c31649355503f7b13d117c68c96523"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "9ff1a261860fcb16a7c7f124d738abcdfc1297363412d237540685003ff04d6b"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "248d96043d3cd40e0d73c02e649d5d55967ebc2ba10e60b58ba75bfba3476425"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "9d340481c374a20067d1748c1a4991626bce9d7812f0bdb96072cd7a15d35462"
metafile = true

[[files]]
file = "mods/status-effect-bars.pw.toml"
hash = "3ed900bdfc8331520c122957c64c930a50bd814a722b6367155af675d4bf0e40"
metafile = true

[[files]]
file = "mods/tweakermore.pw.toml"
hash = "1b7f1613ef6a3bb72c74fa4d5bcbc7c6b9bbf95ccc33b9465d4f31b02227b69b"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "4e83c1af9a9c49d4ca7a67adc6370bcf58fabfa040ace15a62e6e96cdb3064b5"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "3f5679e5212d0cb5e6700b4d13001d435e60fb9151121e01f83d9f10d296eba5"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "71c91341cc8ac8773b839d7ca822d8d7084c11a3012e13a10ef0de6daff93796"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "1113d43c39a9866252a83ee50d16aa3ce6fcf749acd84d58b05ca09eba4d187b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "671e1badbd1d6b1fe20851202a5328f0600534af609afb0b8b1a0840aa222246"
metafile = true

[[files]]
file = "options.txt"
hash = "aabcdf1bb3f4b2304a8be9d01cd90b3e570e6a40842821a0fb78836e0a493b27"

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "b769a2f7ef2fa754224c5068491e79d02c0c85e0bc326fc05247f18315cc866b"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "5caf93fa1624aeb26d11cdbadcb0c03b2a92815c798a930014774c7d525baf28"
metafile = true
