hash-format = "sha256"

[[files]]
file = ".envrc"
hash = "1d26c74fd25a4c3dbb09e029fc609588da499fd4af2a41c88f6316c7f8c54cf1"

[[files]]
file = "config/iris.properties"
hash = "396c4896484b87c8628f07a8083af78855fa441835449d4a94d8ea86b84a40ba"

[[files]]
file = "config/itemscroller.json"
hash = "b9a1997727d4a3001cf589901099f409a54def6e76b23bb81904ee15f4b7c2d3"

[[files]]
file = "config/litematica.json"
hash = "2ce533c7d3b123ffbd5df1b16c630a3dadc23c0bd11d8c739f58f0f45bb60634"

[[files]]
file = "config/litematica/litematica_localhost.json"
hash = "c5084e511824ed9f2f38764243b970bd4c7d1047c5fa450b4f4e1c6a2cf9622e"

[[files]]
file = "config/litematica/litematica_localhost_dim_minecraft_overworld.json"
hash = "4a6809e2e3fd89774626b695a48533eaeee73131af4f27333f09af1807eae2bf"

[[files]]
file = "config/litematica/litematica_localhost_dim_minecraft_the_end.json"
hash = "4a6809e2e3fd89774626b695a48533eaeee73131af4f27333f09af1807eae2bf"

[[files]]
file = "config/litematica/litematica_localhost_dim_minecraft_the_nether.json"
hash = "4a6809e2e3fd89774626b695a48533eaeee73131af4f27333f09af1807eae2bf"

[[files]]
file = "config/litematica/litematica_nerduniverse.duckdns.org.json"
hash = "c5084e511824ed9f2f38764243b970bd4c7d1047c5fa450b4f4e1c6a2cf9622e"

[[files]]
file = "config/litematica/litematica_nerduniverse.duckdns.org_dim_minecraft_overworld.json"
hash = "c6e3dcc4f1f37009b5d9bafd8fe6721bfc62cb5948f0ab0d64175ade83a9e5d6"

[[files]]
file = "config/litematica/litematica_nerduniverse.duckdns.org_dim_minecraft_the_end.json"
hash = "4a6809e2e3fd89774626b695a48533eaeee73131af4f27333f09af1807eae2bf"

[[files]]
file = "config/litematica/litematica_nerduniverse.duckdns.org_dim_minecraft_the_nether.json"
hash = "c6e3dcc4f1f37009b5d9bafd8fe6721bfc62cb5948f0ab0d64175ade83a9e5d6"

[[files]]
file = "config/litematica/litematica_new_world.json"
hash = "12174fd2e7b7105aa4aa98a486df7baa470fd770ff30a731cf314c4fd571701a"

[[files]]
file = "config/litematica/litematica_new_world_dim_minecraft_overworld.json"
hash = "4a6809e2e3fd89774626b695a48533eaeee73131af4f27333f09af1807eae2bf"

[[files]]
file = "config/malilib.json"
hash = "13b137a7e5d3194ccd24f617731ba4aac32237d69067f1f5b8bbb1160e6efe76"

[[files]]
file = "config/minihud.json"
hash = "7e069df522fd7edb611b9b917b1fbccb7b26d9429ff2ec4190513c2e288b8ca1"

[[files]]
file = "config/minihud/localhost.json"
hash = "7d379de5ad06b4471e4b7e62970340437662e77453dd1bacb3bc90f975403464"

[[files]]
file = "config/minihud/localhost_dim_minecraft_overworld.json"
hash = "d52eed27fd155e3c847593668511315c745ad9113ebac783b827f8411c36715c"

[[files]]
file = "config/minihud/localhost_dim_minecraft_the_end.json"
hash = "dd81d0abfde5de7a306ad024b0e6dc984435eb7f14502199cff365a767dbfb2c"

[[files]]
file = "config/minihud/localhost_dim_minecraft_the_nether.json"
hash = "dd81d0abfde5de7a306ad024b0e6dc984435eb7f14502199cff365a767dbfb2c"

[[files]]
file = "config/minihud/nerduniverse.duckdns.org.json"
hash = "7d379de5ad06b4471e4b7e62970340437662e77453dd1bacb3bc90f975403464"

[[files]]
file = "config/minihud/nerduniverse.duckdns.org_dim_minecraft_overworld.json"
hash = "dd81d0abfde5de7a306ad024b0e6dc984435eb7f14502199cff365a767dbfb2c"

[[files]]
file = "config/minihud/nerduniverse.duckdns.org_dim_minecraft_the_end.json"
hash = "dd81d0abfde5de7a306ad024b0e6dc984435eb7f14502199cff365a767dbfb2c"

[[files]]
file = "config/minihud/nerduniverse.duckdns.org_dim_minecraft_the_nether.json"
hash = "dd81d0abfde5de7a306ad024b0e6dc984435eb7f14502199cff365a767dbfb2c"

[[files]]
file = "config/minihud/new_world.json"
hash = "7d379de5ad06b4471e4b7e62970340437662e77453dd1bacb3bc90f975403464"

[[files]]
file = "config/minihud/new_world_dim_minecraft_overworld.json"
hash = "dd81d0abfde5de7a306ad024b0e6dc984435eb7f14502199cff365a767dbfb2c"

[[files]]
file = "config/peek/peek.properties"
hash = "bfa5754e7f8f53ecc85feb1f0eeafde3430d2ea47bc64701d662500c7140bbbd"

[[files]]
file = "config/sdrp-common.json"
hash = "fc5ca865f4f027189b5894c421fd99588e0916f27915d29bb1dcf068a510a28f"

[[files]]
file = "config/tweakeroo.json"
hash = "a53c34fb39f3384eb15b3c799ed0656e620e0525cf336b2ad615eb24cbcb949b"

[[files]]
file = "config/xaerominimap-common.txt"
hash = "1dcee38470c2939f7265891203775b7631c81822bf2506a451727fcaaf2cc4a2"

[[files]]
file = "config/xaerominimap.txt"
hash = "54774cf954b6dc94b2ea96101cc1773a269e51f0c381607ad6c301375acab9a3"

[[files]]
file = "config/xaerominimap_entities.json"
hash = "c63fa9862b71e4d7d39f0ba3c214ec8482c622d960574003eabe56dd021cbead"

[[files]]
file = "config/xaeropatreon.txt"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "config/xaeroworldmap-common.txt"
hash = "103979a8e59e396f99fb8646c4f8a690c2d743ca3744a2eb8f663b3102b7498c"

[[files]]
file = "config/xaeroworldmap.txt"
hash = "6028733f967d0d0f6a80dd236d3dcc7d2446912c719ab9a7d3f83d8624d9b92d"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "904365e7891802e522e5a35189b7039e18f56a22ab30bd99af59b97ec4b7468e"
metafile = true

[[files]]
file = "mods/accurate-block-placement-reborn.pw.toml"
hash = "980d2653a03fdaf15fb652592bcc503bff25dda9e721d627226d091a90a56946"
metafile = true

[[files]]
file = "mods/anti-xray.pw.toml"
hash = "7ffd2cbb973d987d543b36f12cc9362baae07b0983b83a8292f063ed4287f9a9"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "ed50f3b3feba91fa31915aefb40690bc322f37be83490e6b59a443e83a46a542"
metafile = true

[[files]]
file = "mods/autorun.pw.toml"
hash = "a6a3f8e8b127583f0dddf76c4a9aa5e946074c80e0aea94e3453e12e7952a542"
metafile = true

[[files]]
file = "mods/axiom.pw.toml"
hash = "b1e08d3a6db8777433227b2b300c89795d7baced15a012fe256aaddef74e91b6"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "b72d00d529ec694ae354b73f6b36d4ec2b830c60c05cc31f46d00ac7ddf8a26b"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "17e7de63579b066cea4b6db60318617956c1925891edc562085cd72544a763b9"
metafile = true

[[files]]
file = "mods/bigshot.pw.toml"
hash = "d664a21bceb31aae94ef5c73898b0bd5387fd8bef59d24e9ecd54ebe6d53d0c5"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "5ab81359d4654812c2f4dd40f6db5bb51e217a228827d5cc351a40611f05d7de"
metafile = true

[[files]]
file = "mods/bundles-beyond.pw.toml"
hash = "7908a5bd9db4ffcf529f5df1e588982441996082ebe3b8536ba831513dcc5865"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "1b6acd374e376f9dee939184a228eb8b1a8fd1abb5074a8a6cff2473712aeadb"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "092508af534efeb380b9551663980ab1f701d88583a63227d02cb02843335f7a"
metafile = true

[[files]]
file = "mods/chatanimation.pw.toml"
hash = "9854603f767980c514aefe9c391a6d3fa89dc6be18d23ab462f2a3bbabe7652c"
metafile = true

[[files]]
file = "mods/clientsort.pw.toml"
hash = "a2dd570b2ef1ff660000db622edb5a0bebc42e6b2edfe31e95af305bc1a2948c"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "aed9bbc1e24a8db8f57a9bea98460638abf832aaa5281d607657bd3063022348"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "c2a61b492dd0d7a156e15b7572adb40552b94c09658cc3c6d7faf99288d094c7"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "716b671d0b15ea17c788c571620eac83207bb2b6e8dbe0d33319838478f21efc"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "d06bd663c0b321e02f82c2a95f43f7f5e5b704f6b9ce4c7e4067f4d5c9e51245"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "3a96a1e5bef30c16a8738c2a8acf54693225122424c39fa06f589a11ccc83b90"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "6adf5f512651c200a320219c32a3a51c8b95e219206f64b99cb93940d51b2cfa"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "816a274a51586b2a1e328b70fef8aba88c8e0c64205bebb2773cde8bc205f20f"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/fadeless.pw.toml"
hash = "33751edd5b63fdc4d8c51e19a74013efc600807ad8cf773d1512072b97c8ecd7"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "87dea750205910be6e5184ca4cdc3a3f2f439364435408b8e7a1036fdf3c28fc"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "76a12a836d4c7f0f943a1e391dd2d7b5c4673caa497fff16593d49449376b117"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "b22f1d052eee2810fda73d850dd6f425a1214965e03a5a9dada421abfe74603b"
metafile = true

[[files]]
file = "mods/herenthere.pw.toml"
hash = "0d5730b227ad429165ef6b2bbe269e5123b71221bc6b8b0efac56232ace2b0c6"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "402069ebe33a1f19e6e5c0c0235267b832ba44617f15ddbdc677faf2a2607e38"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "43ae42453ad9c79d9ab1158e13b3230f3dd5d43c6abc088f566038152af3347f"
metafile = true

[[files]]
file = "mods/item-scroller.pw.toml"
hash = "8643786cd883f7686a11f2bcc773acbe6559a7d3d13af3ed690e8d7fa58ef343"
metafile = true

[[files]]
file = "mods/ixeris.pw.toml"
hash = "2429bf75e06352fd088cc43f1204b6a106560420c5ff93095820fd0ad64f33fc"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "7cb1f88c44e35ca6a374ce9cf4a82df99843e6109576e0e9bb20ea2a1f5c16f7"
metafile = true

[[files]]
file = "mods/litematicdownloader.pw.toml"
hash = "145c1312278f193aaf0a0853d6a4c95c7dede67c44080d60447800cfbef74fe0"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "88a36b21d538d44aca7dd0a7e5ad8c09b1b263be3f4381e3bb22bc9f94ee7290"
metafile = true

[[files]]
file = "mods/llitematica-quick-share-addon.pw.toml"
hash = "5121d59e9f3fb2acec506149f942a0dd39354187df0ac744b3efc300f1ed89f0"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "c8da9df94366869dacc80807029f14edb4c583420b7b2d5193d6da06e85150ea"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "e1bdd6fe057de088e1aab32b70309185bdfe6f004146067b7b14d4f83fbb207b"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "6dbca2c20d66b076bb4e8959ea0e26887991acf48f785aae402e066d5e3eb6ea"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "820d98a1f8bdcbf5772fda8670d6e353c120a4df8cfb478aa9b744429253a216"
metafile = true

[[files]]
file = "mods/peek.pw.toml"
hash = "a7ed3b70eee552acb382d218b9ab840d6d8d81fac7491db9d146692c4d870389"
metafile = true

[[files]]
file = "mods/ping-view.pw.toml"
hash = "a25ff2b7f1fe489dcecbbcb67907f15f3e1b18892916615050fb1f741c57440c"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "4626f4c13b47099ed0466cc50e1fb526e9b00de88a39e5e11e66be142ff38013"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "f3e9b0ac5a63f905fcf7923e71556e4ee435b858d60f05219e9ea4fcde45694a"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "936e9028071f4e49ecd551aadab4c161f9a7143764b4cc89f8077296bd8645a6"
metafile = true

[[files]]
file = "mods/shuttfup.pw.toml"
hash = "d44432512af8fc6992c273a01e26b9067d26f52b02f4f252476832b69d25851c"
metafile = true

[[files]]
file = "mods/signalloss.pw.toml"
hash = "743040f377b4f1e5b8f59764eeca73a4c2c31649355503f7b13d117c68c96523"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "5936eea7a83a33027fae99530fec0fa76511ee1ecbfee8125944ba1f470e7713"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "248d96043d3cd40e0d73c02e649d5d55967ebc2ba10e60b58ba75bfba3476425"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "c0a85192cfec296d8ab8690e91bfeb932efde590af289ec263616ed36543cee7"
metafile = true

[[files]]
file = "mods/status-effect-bars.pw.toml"
hash = "3ed900bdfc8331520c122957c64c930a50bd814a722b6367155af675d4bf0e40"
metafile = true

[[files]]
file = "mods/tweakermore.pw.toml"
hash = "060b425b0055d87f793f7f8325aa8ad637cb84dd4b33a2908646372e201d5f9b"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "d80f469d856cb34a20556543c9c0617bcf83a259cf6a3822104f84883c9879a3"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "d21872a45afdb441d7124afce6d80bd01714ba13ac6956e4adf5003b353f1059"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "34fea802d614ca9d67ee54693a23ba5d91a3728510db404c88140098eb38860f"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "6b2e6c4faa6fa928c5c5c582752b80401e418d4f897839b7d0338acc08e94803"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "d74d244b3524bea2326becd2ceaa27b8e231156aba33448533cd29b12ed48318"
metafile = true

[[files]]
file = "options.txt"
hash = "40efb3f53dabcc091e4fa10b9c35d24771e58373979765af623e42467a12ea79"

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "134b3cee2ac2b5c5b9d02d8d70e8e4ba32c7c241f5bc51209521831a7c254e22"
metafile = true
