name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "757de4925622ccd7974a68aa933a08a3ec4cfda3923433d0715997b17750f249"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
