name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edb1b25a43417335a24b461f5ade8773c6617a07ae694643668ec77dbc37ae7e"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
