name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4880b6064ba177ce95bf99ab6a4f077b5d6d26f1220979bda20645a432251e97"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
