name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9d066c442dfa33b710dbc433c486ee29dcc115055e557185f11a2fdfd57f1a0"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
