name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a440a0f211e57ff8f080720e984d0126e6d33c2664c7a4d14e36e7d0a5f4374"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
