name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc8f755b956871c4ea46cc150ed34269ae9e8af9140dfd901953a3ff6664be8e"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
