name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ddcbc55bb934201b6e97c5d4780842f8518e97955ab55b6723c25174f9daab6"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
