name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c14e7d3fe86887b5ed7d7cf21b1a0766184dd9ba687c293a0c1b2e25de9fa33e"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
