name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10cad8a3373ce32e14b23bf09c48d5003be56861d3463b6ca9349341c4618d25"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
