name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcc5ae2e93d4a123b9dfd968df7a5805d4e7fb1ce59bcadad5be7e97b5f9f25a"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
