name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1dadd0c78e0a4e6c91672d2a426424643e5285876700f6402b8676a3c4d9fb72"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
