name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ded21368eb1999db4441f98928fc87cbd3befe2ddffb1f93ad52d997d926aad4"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
