name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5470e3235a50f17babbe9fd1b1e1487fcc8e82439c132c96757dc2748e7dd09"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
