name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "638e4ca5cc1d5b586a80ed6ddf299acbc409f7c70d252f4593eddb2ede4f60e1"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
