name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47f2e229e2aeac68f4b570a4abc85868811790103604711e7f09aadad3101554"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
