name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81ee3ec3c5cec6cd7b681f40cd32592ff73f74eb50fdcdfc3337b435e253cd3c"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
