name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "638ba79dd08384e00de8cdadd4d02900f0dc88b5cb04f4126fb633f4c121b555"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
