name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cee99bd0982c21878bb4a1bfcd5c92d1c3280e262b2ba71bf8295d830eb0bc5a"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
