name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9dba50020e4fa4b48a5611f27f45229787f65460e3f38734788ee1531185e384"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
