name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eae8f4234ceeb876dc41d6abbb3e240187bcc037dfd2fff6477229b12482eec9"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
