name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43d8d5f63785d0eb632fc189c38d5b97be71388351ec2f205353aecfd64876a6"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
