name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "047b25289f20430aa0a9b8ab1fbb62f787fabc62a98ccb2e72e1afb91cef3f0e"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
