name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1c02ffb4bab0475a17d8ccd78d21a06230ed3b75fb93bbedc1fe143aec73039"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
