name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49e3cf328c92ed9bb368073377f088885750dbd31464288adf13216e97ac1f30"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
