name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ecd391fdca334c3c65e87a61ce608dc623b810035a822cfc7ce1a5319014aa3"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
