name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41a246fe0275c6c44f4c3ac5798d8045e5afe44d09e245d64e7406da98d186c5"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
