name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f64cdb89ba60c8c68d03cd3cb15c0c07a3f801d0183f6afc46eda83b50683454"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
