name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7de744f8f9582b841f36a0faa9d8192a86b2ef6b28c988a2d62dea6266135c56"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
