name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d70a65671db963eab996ab69d200721059d24f03e79a969a0f4d3b7a4bf4c76"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
