name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c406a8803dbe2dae21a42bd39c57db20339680dcb73fcf0d0e5c5be27cf55ee"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
