name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69fd8827c9ac1f740f7d474518357d8be45662aac6767c678cc4495f0a432afa"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
