name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23d9aaa96a9b4b1651f038d39bc64d4ed2fa936c4dfdc0c02ea0ff28bf667536"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
