name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d09f8d34ba620346b18c38eb7908cedd00bdb7e7a045caa400a26e87cb324955"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
