name = "Nico's Survival Modpack"
author = "Nicoladen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6d0486e3252f8e5dbff1434b3cf58ea4cdcbaabe10261f981ca20fef7cc9c52"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
